#!/bin/bash
set -eo pipefail

prepare () {
  aws --profile offen --endpoint-url https://storage.offen.dev s3 cp $1 .
}

update_services () {
  docker-compose pull
  docker-compose down
  docker-compose up -d
}

cleanup () {
  # this makes sure we do not keep old image layers
  docker image prune -f
}

check_deps () {
  local deps=("aws" "docker" "docker-compose")
  for dep in "${deps[@]}"; do
    if [ ! -x "$(which $dep)" ]; then
      echo "This script requires $dep, which is not installed. Cannot continue."
      exit 1
    fi
  done

  set +e
  docker info > /dev/null 2>&1; ec=$?
  set -e
  if [ "$ec" != "0" ]; then
    echo "Docker daemon not running, cannot continue."
    exit 1
  fi
}

cd $(dirname $0)
check_deps
prepare $1
update_services
cleanup
