#!/bin/bash
set -eo pipefail

prepare () {
  aws s3 cp $1 .
}

update_services () {
  docker-compose pull
  docker-compose down
  docker-compose up -d
}

cleanup () {
  # this makes sure we do not keep old image layers
  docker image prune -f
}

check_deps () {
  if [ -z "$(which aws)" ]; then
    echo "AWS cli not installed, cannot continue."
    exit 1
  fi

  if [ -z "$(which docker)" ]; then
    echo "Docker not installed, cannot continue."
    exit 1
  fi

  set +e
  docker info > /dev/null 2>&1; ec=$?
  set -e
  if [ "$ec" != "0" ]; then
    echo "Docker daemon not running, cannot continue."
    exit 1
  fi

  if [ -z "$(which docker-compose)" ]; then
    echo "docker-compose not installed, cannot continue."
    exit 1
  fi
}

cd $(dirname $0)
check_deps
prepare $1
update_services
cleanup
