# Copyright 2020-2021 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: Unlicense

version: '2.3'

services:
  backup:
    image: offen/docker-volume-backup:v1.8.2
    restart: always
    env_file: ./backup.env
    logging:
      driver: syslog
      options:
        tag: offen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - db:/backup/offen-db:ro

volumes:
  db:
