# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: MIT

version: '2.3'

services:
  offen:
    image: offen/offen@sha256:cca2fb22e78aca6fb1e67c8b93ac57cb34e2eb64c87b33cec5cb33c45b106943
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ./offen.env
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
    logging: &default_syslog
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

  backup:
    image: futurice/docker-volume-backup@sha256:b2e6e796ad54853afa54dc474da8db2f24a6f45ba46781feb15500df2a3c1b5d
    restart: always
    environment:
      BACKUP_CRON_EXPRESSION: '0 2 * * *'
      BACKUP_FILENAME: offen-db-%Y-%m-%dT%H-%M-%S.tar.gz
    env_file: ./backup.env
    logging: *default_syslog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - db:/backup/offen-db:ro

  expire:
    build:
      context: ./expire
    restart: always
    env_file: ./backup.env
    logging: *default_syslog

volumes:
  db:
  certs:
