version: '2.3'

services:
  offen:
    image: offen/offen@sha256:472f459f40fafaf88264b52f06f60f4457c54f28d251bea820e091d65bf1ce96
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      OFFEN_SERVER_AUTOTLS: 'offen.offen.dev,offen.frederikring.com,analytics.offen.dev'
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
      - ./offen.env:/etc/offen/offen.env
    logging: &default_syslog
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

  backup:
    image: futurice/docker-volume-backup@sha256:b2e6e796ad54853afa54dc474da8db2f24a6f45ba46781feb15500df2a3c1b5d
    environment:
      AWS_DEFAULT_REGION: eu-central-1
      AWS_S3_BUCKET_NAME: offen-db-backups
      BACKUP_CRON_EXPRESSION: '0 2 * * *'
      BACKUP_FILENAME: offen-offen-dev.tar.gz
    env_file: ./offen.env
    logging: *default_syslog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - db:/backup/offen-db:ro

volumes:
  db:
  certs:
