# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: MIT

version: '2.3'

services:
  offen:
    image: offen/offen@sha256:afcca9d1b792a260fd9b8eda1adf53e9d7ee6cbdc09d8612ef98a4eae2be1200
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ./offen.env
    environment:
      OFFEN_ARGONNUMCPUOVERRIDE: '1'
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
    logging:
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

volumes:
  db:
  certs:
