# Copyright 2020-2021 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: Unlicense

version: '2.3'

services:
  offen:
    image: offen/offen:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ./offen.env
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
    logging:
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

  backup:
    image: offen/docker-volume-backup:v2.9.0
    restart: always
    environment:
      BACKUP_CRON_EXPRESSION: '0 2 * * *'
      BACKUP_FILENAME: 'offen-db-%Y-%m-%dT%H-%M-%S.tar.gz'
      BACKUP_LATEST_SYMLINK: 'offen-db-latest.tar.gz'
      BACKUP_PRUNING_PREFIX: 'offen-db-'
      BACKUP_RETENTION_DAYS: '7'
    logging:
      driver: syslog
      options:
        tag: offen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - db:/backup/offen-db:ro
      - ./backups:/archive

volumes:
  db:
  certs:
