version: '3'

services:
  offen:
    image: offen/offen@sha256:a20272daa4c455252c3e8b31c80c3bf140e0c538e6912483eeadfb925912ca6a
    restart: on-failure
    volumes:
      - db:/var/opt/offen
      - certs:/var/www/.cache
      - ./offen.env:/etc/offen/offen.env
    ports:
      - 80:80
      - 443:443
    environment:
      OFFEN_SERVER_AUTOTLS: 'analytics.offen.dev,offen.frederikring.com,offen.taell.me,offen.niefeld.com'
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: production

volumes:
  db:
  certs:
