# Copyright 2020-2021 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: Unlicense

version: '2.3'

services:
  offen:
    image: offen/offen:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ./offen.env
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
    logging:
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

volumes:
  db:
  certs:
