version: '2.3'

services:
  offen:
    image: offen/offen@sha256:a20272daa4c455252c3e8b31c80c3bf140e0c538e6912483eeadfb925912ca6a
    restart: on-failure
    volumes:
      - db:/var/opt/offen
      - certs:/var/www/.cache
      - ./offen.env:/etc/offen/offen.env
    ports:
      - 80:80
      - 443:443
    environment:
      OFFEN_SERVER_AUTOTLS: 'analytics.offen.dev,offen.frederikring.com,offen.taell.me,offen.niefeld.com'
    # By default, Docker will allow for too much memory too be allocated on
    # the 512M t3.nano that is currently in use, so the Linux kernel will
    # needlessly OOM kill the process from time to time when doing system tasks.
    # Allowing Offen to use 256M only is sufficient for the service and the OS
    # to co-reside in peace while keeping the service running.
    mem_limit: 256M
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: production

volumes:
  db:
  certs:
