version: '3'

services:
  offen:
    image: offen/offen:latest
    restart: on-failure
    volumes:
      - db:/var/opt/offen
      - certs:/var/www/.cache
      - /home/ubuntu/offen.env:/etc/offen/offen.env
      - /home/ubuntu/bootstrap.yml:/root/bootstrap.yml
    ports:
      - 80:80
      - 443:443
    environment:
      OFFEN_SERVER_AUTOTLS: 'analytics.offen.dev,offen.frederikring.com,offen.taell.me,offen.niefeld.com'
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: production

volumes:
  db:
  certs:
