# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: MIT

version: '2.3'

services:
  offen:
    image: offen/offen@sha256:b9bde56c8588a092b1c226f610de580694fe390a8d480342e07a2c0b7aad5a2e
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ./offen.env
    environment:
      OFFEN_ARGONNUMCPUOVERRIDE: '1'
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
    logging:
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

volumes:
  db:
  certs:
