# Copyright 2020-2021 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: Unlicense

version: '2.3'

services:
  offen:
    image: offen/offen@sha256:235a91902258724d7eaf2340ef2d167e062d0070479b71c717ea450141dc2280
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ./offen.env
    environment:
      OFFEN_ARGONNUMCPUOVERRIDE: '1'
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
    logging:
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

volumes:
  db:
  certs:
