# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: MIT

version: '2.3'

services:
  offen:
    image: offen/offen@sha256:07c7520c783a59833cf7065cc3b2607d18a5a23a2e046257540ede4edfb793b3
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ./offen.env
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
    logging:
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

volumes:
  db:
  certs:
