version: '3'

services:
  offen:
    image: offen/offen@sha256:79f90845209fe8c36f880517f1a0a109fc541e0f89be280da1d356886bcfcf74
    restart: on-failure
    volumes:
      - db:/var/opt/offen
      - certs:/var/www/.cache
      - ./offen.env:/etc/offen/offen.env
    ports:
      - 80:80
      - 443:443
    environment:
      OFFEN_SERVER_AUTOTLS: 'analytics.offen.dev,offen.frederikring.com,offen.taell.me,offen.niefeld.com'
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: production

volumes:
  db:
  certs:
