version: '2.3'

services:
  offen:
    image: offen/offen@sha256:9479f456883e7b805346ba304b6f81cae83a69d77b8add8da816300337db3db9
    restart: on-failure
    volumes:
      - db:/var/opt/offen
      - certs:/var/www/.cache
      - ./offen.env:/etc/offen/offen.env
    ports:
      - 80:80
      - 443:443
    environment:
      OFFEN_SERVER_AUTOTLS: 'analytics.offen.dev,offen.frederikring.com,offen.taell.me,offen.niefeld.com'
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: production

volumes:
  db:
  certs:
