version: '2.3'

services:
  offen:
    image: offen/offen@sha256:ba071e18d3c34328f6770cdeb8ac917dd1c3af338314892e44eb024351e42b7a
    restart: on-failure
    volumes:
      - db:/var/opt/offen
      - certs:/var/www/.cache
      - ./offen.env:/etc/offen/offen.env
    ports:
      - 80:80
      - 443:443
    environment:
      OFFEN_SERVER_AUTOTLS: 'analytics.offen.dev,offen.offen.dev,offen.frederikring.com,offen.taell.me,offen.niefeld.com'
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: production

volumes:
  db:
  certs:
