# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: MIT

version: '2.3'

services:
  backup:
    image: futurice/docker-volume-backup@sha256:b2e6e796ad54853afa54dc474da8db2f24a6f45ba46781feb15500df2a3c1b5d
    restart: always
    environment:
      BACKUP_CRON_EXPRESSION: '0 2 * * *'
      BACKUP_FILENAME: offen-db-%Y-%m-%dT%H-%M-%S.tar.gz
    env_file: ./backup.env
    logging:
      driver: syslog
      options:
        tag: offen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - db:/backup/offen-db:ro

volumes:
  db:
