version: '3'

services:
  offen:
    image: offen/offen@sha256:bf75b246600efbe8e0eb7f0c6c03a0700e78b05310be26556375c10187b0b852
    restart: on-failure
    volumes:
      - db:/var/opt/offen
      - certs:/var/www/.cache
      - ./offen.env:/etc/offen/offen.env
    ports:
      - 80:80
      - 443:443
    environment:
      OFFEN_SERVER_AUTOTLS: 'analytics.offen.dev,offen.frederikring.com,offen.taell.me,offen.niefeld.com'
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: production

volumes:
  db:
  certs:
