# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: MIT

version: '2.3'

services:
  offen:
    image: offen/offen@sha256:fd26a4873e02e0e865cefec2cbdf9efdf6542fbedfe3ce909a949b5ec061bc67
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ./offen.env
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
    logging:
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

volumes:
  db:
  certs:
