# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: MIT

version: '2.3'

services:
  expire:
    build:
      context: ./expire
    restart: always
    env_file: ./backup.env
    logging:
      driver: syslog
      options:
        tag: offen
