# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: MIT

version: '2.3'

services:
  offen:
    image: offen/offen@sha256:077170c56ad4464a3347318e286a253682b1ed4020a1fd22ab9ac8c5a727a2b4
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ./offen.env
    volumes:
      - certs:/var/www/.cache
      - db:/var/opt/offen
    logging:
      driver: syslog
      options:
        tag: offen
    labels:
      - docker-volume-backup.stop-during-backup=true

volumes:
  db:
  certs:
