version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:2020.06
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'c3:09:7c:f4:a5:2c:66:45:79:53:f4:b4:ce:42:e7:bf'
      - checkout
      - run:
          name: Run keyscan
          command: |
            ssh-keyscan -H offen.offen.dev >> ~/.ssh/known_hosts
      - run:
          name: Configure git
          command: |
            git config --global user.email "hioffen@posteo.de"
            git config --global user.name "Offen Deploy Bot"
            git remote add deployment root@offen.offen.dev:offen/deployment.git
      - run:
          name: Push to deployment
          command: |
            git push deployment offen-offen-dev -f 2>&1 | tee out.txt
            grep -v "ERR_DEPLOYMENT_FAILED" out.txt > /dev/null
      - run:
          name: Check service health
          command: |
            curl -sS https://offen.offen.dev/healthz

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - offen-offen-dev
